### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by TheStolenBattenberg** [Geomitron/Bridge#15]
I leave my PC on overnight, usually that's fine. This morning after waking up I'd found my PC responding terribly, Ctrl+Alt+Delete and what the heck: [Image of taskmanager](https://pasteboard.co/JW3oVsy.png)

To retrace my steps a little so you might find the problem -
1. Tried to download a bunch of Megadeth
2. Bridge tells me I already have the song I've selected
3. Unselect that song
4. Bridge tells me I STILL have the song selected
5. Close bridge
6. Wait 10 - 20 Hours

Thanks for the work and effort you're putting in to once and for all destroy the horrible effort that is installing new charts.

**Comment by Geomitron** [comment]
Thanks for reporting it. About how many charts did you try to download? I know that I haven't optimized the downloads screen for a large number of concurrent downloads. Also, did you actually close Bridge before leaving it on overnight? Was the window closed and the program running in the background?

**Comment by NeonLightning** [comment]
i had downloaded a few files and had 6 downloads going and and it was using 4.5 gig of ram after an hour.

**Comment by TheStolenBattenberg** [comment]
> Thanks for reporting it. About how many charts did you try to download? I know that I haven't optimized the downloads screen for a large number of concurrent downloads. Also, did you actually close Bridge before leaving it on overnight? Was the window closed and the program running in the background?

I started small, only 3 songs as I didn't want to max out my google download limit. I don't think bridge was fully closed if it stays open in the background, I did close the window with the cross though.

**Comment by Geomitron** [comment]
Yeah, this is definitely a memory leak. I'll be finding and fixing this right after the next update, as well as improving performance when a lot of charts are in the download queue.

**Comment by Geomitron** [comment]
I've investigated the issue; it looks like none of this extra memory is getting added to the javascript heap in the electron process or the browser process. This means the leak is happening somewhere inside Electron, Nodejs, or a library I'm using, which is all code that I am unable to modify. There's a chance that it's caused by me misusing those technologies, but I've looked over their usage and couldn't find anything I was doing wrong. The fact that the memory isn't getting added to the javascript heap means this is almost impossible to debug. I've made some changes that might help, and I'll keep an eye on memory usage, but I've decided to move on to other features and improvements for now.

**Comment by TheStolenBattenberg** [comment]
That's very curious indeed. I keep testing from time to time and report any improvements here for you.

**Comment by blackshot** [comment]
You are in time for migrating to tauri

**Comment by Geomitron** [comment]
In v2.0, the download process has been reworked, and I'm not seeing this problem so far, so I'll mark this as fixed. If you still encounter problems, open another issue or mention it on the Discord.
