### ISSUE TITLE
Installing on Windows shows Windows SmartScreen warning

### ISSUE THREAD

**Issue by sepcol** [Geomitron/Bridge#16]
Windows version: 20H2

**Comment by Geomitron** [comment]
In order to remove this, I essentially need to pay Microsoft to verify the application (which costs $100 to $700 per year), or just wait long enough for the application to get added to their "approved" list. I don't think that price is worth it for just removing a warning message. If you or anyone else is concerned, you can always download the source code and compile it yourself. It's fairly straightforward:
- Install the latest version of Node.js
- Download the source code
- Run `npm install` in the root project folder to install dependencies
- Run `npm start` in the root project folder to launch it in development mode, or
- Run `npm run build:windows` in the root project folder to compile the installer to the `./release` folder
