### ISSUE TITLE
"Sign in with Google" to remove rate limit delay returns `Error 401: disabled_client`

### ISSUE THREAD

**Issue by ASchneider-GitHub** [Geomitron/Bridge#34]
After using Bridge for a bit, I tried signing into Google to remove the rate limit delay, and was given the following error once sign-in was complete:

> Error 401: disabled_client
>Sign in with Google temporarily disabled for this app. This app has not been verified yet by Google in order to use Google Sign In.
>
> The content in this section has been provided by the app developer. This content has not been reviewed or verified by Google.
> If you’re the app developer, make sure that these request details comply with Google policies.
> ```access_type: offline
> response_type: code
> redirect_uri: http://127.0.0.1:42813/oauth2callback
> client_id: 668064259105-vkm77i5lcoo2oumk2eulik7bae8k5agf.apps.googleusercontent.com
> scope: https://www.googleapis.com/auth/drive.readonly```

This occurs with the most recent release of the program (v1.4.2)

**Comment by Geomitron** [comment]
Google changed how OAuth2 works, which broke the feature. Downloading files without verifying the app was never officially supported, but I was keeping Bridge in "development mode" to get access to that without verification. (Verification requires a website, Privacy Policy, and paying thousands of dollars to Google, all of which is only necessary here because of a bug that I reported already: https://issuetracker.google.com/issues/168687448)

Here are the options:
- Download without logging in (the rate limit delay can be set to 0 if you aren't downloading more than 10-20 charts at a time)
- Wait for the bug to be fixed (you can visit the issue tracker page and star it; that may encourage them to get to it more quickly)
- Abandon Google Drive and have my own file hosting system. This is the best option, but also costs money. I'm leaning towards doing this when I get time to work on Bridge again.

**Comment by billxsand** [comment]
No worries! it's actually not a huge deal. I feel like it's an issue only if you are downloading lots of separate tracks, which usually only happens once (when the user is starting to build their library). 

Another option, obviously not for everybody, is VPN. I set my delay limit to 0 and just switched VPN servers every 5-10 minutes once the downloads start returning error 401. My VPN of choice is Private Internet Access. Again, not for everybody, but definitely a solution, and I got through my downloads in about 30 minutes.

>Abandon Google Drive 

IMO it's simply not an option at this point. BUT as a date preservationist the whole Google Drive situation is pretty sketchy :|  Every single CHORUS song should be archived ASAP

**Comment by saadbruno** [comment]
Wouldn't it be possible to let the users create their own Client ID and secret?
That's what RClone does for google drive.

Sure it's not ideal (especially for non tech savvy users), but it's an alternative.

**Comment by saadbruno** [comment]
A made a very crude proof of concept of what that could look like:
![image](https://user-images.githubusercontent.com/23201434/224351346-1f0eb831-564d-4eb8-b392-099fbb822f7c.png)

Right now it half works, as I'm not too familiar with Angular and Electron. It does work, but you need to restart the app so that the google log-in pop up can read the custom client id and secret (i don't really know why, since it works fine when printing to the console)

If this is something we're interested in merging, I can look into refining this and creating a Pull Request

You can see the changes at
https://github.com/saadbruno/Bridge/tree/custom-google-clinet-id

**Comment by Geomitron** [comment]
I've waited for this issue to be fixed, and at this point I'm implementing my own version of chart downloading that doesn't involve the user logging in to Google. The Google login has been removed from the latest version. I'm actively working towards this solution now, but unfortunately there will still be a period of time where downloads will just need to be slow.
