### ISSUE TITLE
[Feature Request] Sort by upload date

### ISSUE THREAD

**Issue by budokaiman** [Geomitron/Bridge#53]
It would be nice to have a sortable upload date column.
If the sort method is changed, there doesn't seem to be any way to revert to sort by most recent. It would also be nice to be able to quickly see the date when checking for new songs or to sort by oldest first to browse all songs without missing new additions.

**Comment by Geomitron** [comment]
The default search (that displays when nothing is in the search bar) is sorted by upload date.
The way to revert the sort is to change the text in the search bar. But that's not the most intuitive thing, so I may change it.
If you're looking for getting "all charts", or a large group of them, I'll be adding a better way to do that at some point in the future.

**Comment by budokaiman** [comment]
> I'll be adding a better way to do that at some point in the future.

Could you elaborate on that a bit? I decided to try browsing sorted by artist, but it seems that it just sorts the displayed page, and then re-sorts after next page load, so the app is only really useful as a "latest uploads" or a search which isn't really helpful when just trying to see what's available.

**Comment by Geomitron** [comment]
I'm not sure; figuring that out is part of the work of creating it, which I don't have time for right now. Maybe it can download every result of an advanced search (without the current 250 result cap)

It would be helpful if you gave more details on how you want to "see what's available" and how that's different from what you can currently do. Because there are a lot of things you can set in the advanced search, which I believe can help narrow down what you're looking for.

**Comment by budokaiman** [comment]
Yeah, I'll show some screenshots from how I use customsforge for rocksmith
By default, the search page sorts by the most recently updated date
![image](https://github.com/Geomitron/Bridge/assets/2196125/fbc0e091-4dcd-449b-80e7-fe5d9ea21afb)

Typically what I'll do is, sort by the oldest added
![image](https://github.com/Geomitron/Bridge/assets/2196125/578950de-e688-41f5-9851-73c5502014a1)

This lets me search from the beginning of time without having to worry about missing anything, like if I sorted by artist since new results would get inserted in the middle. I can also more easily resume browsing later. Since CF has settable page numbers, I'll usually just jot down whatever page I was on, and then just check once a month or whatever for new songs. CF also does have the ability to show which songs have been downloaded or not via icon on the download box (in below example, top has been downloaded, bottom has not and is available for download)
![image](https://github.com/Geomitron/Bridge/assets/2196125/84d75ff3-e599-46ae-b815-bc914d55bf7f)

While bridge has the ability to search for modified after, which would help in resume browsing, it still makes it difficult to discover the older uploads as there's no filter on uploaded/modified before date. I'd essentially like to browse everything uploaded (though narrowed down to drums, which brings up another question, is there any differentiation in search for drums vs pro-drums?) and pick through songs I like, then get new songs as they're added after initial browse.

**Comment by Geomitron** [comment]
I'll consider what you're trying to do when making changes in the future. I also have plans to add a filter for different drum types.

**Comment by Geomitron** [comment]
It seems like sorting by upload date isn't really what you're looking for, you're just using that to see all results and make sure you didn't miss any. I've already set the advanced search to sort by upload date by default, which should allow you to easily check for new stuff. So the challenge is how to allow you to browse and choose from all the existing charts from your search. This is what I want advanced search to handle. This can be fixed if I remove the 250 result advanced search limit. (this is difficult due to technical and performance limitations, but should be possible)

Once that's done, you'll be able to do an advanced search, sort by name, and scroll through the list. You can write down the name you left off at, just like the page number on customsforge.
