### ISSUE TITLE
error

### ISSUE THREAD

**Issue by tomgames2008** [Geomitron/Bridge#69]
![Schermafbeelding 2024-06-13 163148](https://github.com/Geomitron/Bridge/assets/93604569/b5977cfb-9746-4b67-91e8-26e12523c1f9)
uhhh, what does this mean and how do i fix it?
(i just installed it, and when i try to open it, i get this)

(also, lmao i got number 69)

**Comment by Geomitron** [comment]
If you're still having this problem, it's caused by the application failing to access the filesystem. If it's a consistent problem, it's due to the application lacking sufficient permissions. In the next version, this error will be hidden, and instead your settings will fail to save if you change them without fixing the permissions issue.
